In [ ]:
import numpy as np

def hilbert(m, n):
  H = np.zeros((m, n))
  for i in range(m):
    for j in range(n):
      # Add 1 to the indices, because in Python they start from zero
      H[i, j] = 1 / (i+1 + j+1 - 1)
  return H

print(hilbert(2,3))

[[1.         0.5        0.33333333]
 [0.5        0.33333333 0.25      ]]


In [ ]:
#power method is the method to find max eigenvalue and eigenvector
def powmethod(A, x0, itmax, tol=1e-8):
  x = x0
  lam_old = 0

  x = A @ x
  x = x / np.linalg.norm(x)
  lam = x.T @ A @ x

  err = np.abs(lam - lam_old)
  i = 1 # Iteration counter

  while err>tol and i<itmax:
    lam_old = lam
    x= A @ x
    x = x / np.linalg.norm(x)
    lam = x.T @ A @ x

    err= np.abs(lam - lam_old)
    i += 1 # Iteration counter


  return lam, x

A = hilbert(4,4)
x0 = np.ones(4)

eigenval, eigenvector = np.linalg.eig(A)
print('np.linalg.eig:\n', eigenval[0], eigenvector[:,0])
lam, v = powmethod(A, x0, 20)
print('powmethod:\n', lam, v)

np.linalg.eig:
 1.5002142800592424 [0.79260829 0.45192312 0.3224164  0.25216117]
powmethod:
 1.500214279971216 [0.79260356 0.45192613 0.32242054 0.25216535]


In [ ]:
# JACOBI METHOD
import numpy as np

def jacobi(A, b, x0, maxit, tol=1e-6):
  d = np.diag(A)
  N = np.diag(d) - A


  i=0 
  err= tol*2

  x = x0

  while (i<maxit) and (err>tol):
    xold = x 
    v = N @ x + b
    x = v / d

    err = np.linalg.norm(x- xold)
    i += 1
  
  if err < tol:
    print('Converged in ', i, ' iterations')
  else:
    print('Did not converge')
  
  return x


n = 5
A = hilbert(n, n) + 2 * np.eye(n)


# 2*np.eye(n) is added to make A diagonally dominant

b = np.ones(n)
x0 = np.zeros(n)
x = jacobi(A, b, x0, 20)
print('jacobi:\n', x)
print('np.linalg.solve:\n', np.linalg.solve(A, b))

Converged in  17  iterations
jacobi:
 [0.19039346 0.29214789 0.33942537 0.36816475 0.38781483]
np.linalg.solve:
 [0.1903934  0.29214782 0.33942531 0.3681647  0.38781478]
